### ISSUE TITLE
type name is not allowed. 'PaneFlags': illegal use of this type as an expression	

### ISSUE THREAD

**Issue by moebiussurfing** [aiekick/ImTools#3]
![image](https://github.com/aiekick/ImTools/assets/2106149/740d65ce-76ee-4f28-b88e-2f3d7730dbce)

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2275	'PaneFlags': illegal use of this type as an expression	10_ImToolsLayoutManager	C:\Users\moebi\Documents\openFrameworks\addons\ofxSurfingImGuiExtra\0_NewExamples WIP\10_ImToolsLayoutManager\src\ImLayoutManager\RightPane.cpp	63
```

Hey @aiekick , 
I am just trying to port your `LayoutManager` class to my openFrameworks projects,
do you know maybe how can I fix these errors?

I remember make this work some time ago, maybe bc was a previous compiler version?
I am in Windows 11 with Visual Studio 2022.

**Comment by aiekick** [comment]
because the symbol ImGui::Begin<T> is not defined...

i just fixed this old sample.
